prompt_templates:
  summary:
    description: "总结文章的内容"
    template: |
      给你以下的文章内容，该文章来自某本书的某一个章节，或者章节的某一个部分。
      请你分析并总结文章的内容，要求脉络清晰，关键点表述明确，文字流畅，情节完整，
      关键细节以及核心观点不要缺失，有点睛之笔请高光显示。请尽可能详细地总结内容。
      希望输出尽可能完整，不要省略任何重点。
      
      {text}

  oral_draft:
    description: "根据输入的内容生成适合口播的稿件"
    template: |
      给你以下某本书的内容，请你生成适合做视频口播的稿件，请满足以下要求：
      1. 尽可能生成详细的内容，输出尽可能的完整。
      2. 不要任何镜头等额外内容，不是让你做个完整的视频。
      3. 请完全按照文章内容来生成，并且保证不要漏掉任何细节。
      4. 最后，请生成详细的口播稿件，完整稿件不少于1000字。
      
      {text}

  merge:
    description: "将多个章节的总结内容拼接在一起"
    template: |
      请你将下面的内容合并到一起，不要减少任何内容，请注意，上下文的衔接要顺畅，过渡要丝滑，不需要有情节上的割裂感。
      最终内容的数量要不少于1w字。
      
      {text}